### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by darklicius** [Ezzpify/SteamBulkActivator#16]
not working

**Comment by djreisch** [comment]
Yep, exact error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamBulkActivator.MainForm.connectToSteam()
   at SteamBulkActivator.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by darklicius** [comment]
this dev abandoned this project

**Comment by djreisch** [comment]
I saw he made a comment it was because most of the Steamworks SDK is available from Valve. Maybe Ezzpify will be able to convert his code to interact with the official Client SDK from Steamworks.

**Comment by Ezzpify** [comment]
Fixed
